apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: aggress-dev
  labels:
    app: redis
    environment: development
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: aggress-dev
  labels:
    app: elasticsearch
    environment: development
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: http
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: transport
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: aggress-dev
  labels:
    app: kafka
    environment: development
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: aggress-dev
  labels:
    app: zookeeper
    environment: development
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: zookeeper
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: tor-proxy
  namespace: aggress-dev
  labels:
    app: tor-proxy
    environment: development
spec:
  type: ClusterIP
  ports:
    - port: 8118
      targetPort: 8118
      protocol: TCP
      name: privoxy
    - port: 9050
      targetPort: 9050
      protocol: TCP
      name: tor
    - port: 9051
      targetPort: 9051
      protocol: TCP
      name: tor-control
  selector:
    app: tor-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: aggress-dev
  labels:
    app: frontend
    environment: development
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
    - port: 8000
      targetPort: 8000
      nodePort: 30800
      protocol: TCP
      name: debug
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: webadmin
  namespace: aggress-dev
  labels:
    app: webadmin
    environment: development
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP
      name: http
  selector:
    app: webadmin
---
apiVersion: v1
kind: Service
metadata:
  name: crawler
  namespace: aggress-dev
  labels:
    app: crawler
    environment: development
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: debug
  selector:
    app: crawler