# Front-end
#
# VERSION               0.0.1

FROM java:8-jre-alpine
MAINTAINER Iouri Goussev
LABEL Description="Web interface" Vendor="Aggress" Version="LATEST"


CMD java
# HEALTHCHECK --interval=5m --timeout=3s \
#  CMD curl -f http://localhost/ || exit 1