#!/usr/bin/with-contenv sh
set -e

# Wait until another Consul server is available.
# consul-available

CLASSPATH=$(find "/opt/crawler" -name '*.jar' | xargs echo | tr ' ' ':')
exec s6-setuidgid crawler java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000 -Djdk.tls.allowUnsafeServerCertChange=true -Dsun.security.ssl.allowUnsafeRenegotiation=true -cp ${CLASSPATH} com.naxsoft.Crawler -createESIndex -createESMappings -clean -populate -crawl -parse