version: '2'
volumes:
  crawler_volume:
  web_volume:
  elasticsearch_volume:
  redis_volume:

services:
  frontend:
    labels:
        com.naxsoft.frontend.description: "Web interface"
    container_name: frontend
    build: frontend
    ports:
      - "8080:8080"
    links:
      - elasticsearch
    volumes:
      - web_volume:/opt/project
    depends_on:
      - elasticsearch
    env_file:
      - common.env

  crawler:
    labels:
        com.naxsoft.crawler.description: "Web crawler and indexer"
    container_name: crawler
    build: crawler
    links:
      - elasticsearch
      - redis:database
    volumes:
      - crawler_volume:/opt/project
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - common.env

  elasticsearch:
    labels:
        com.naxsoft.elasticsearch.description: "Search engine"
    container_name: elasticsearch
    build: elasticsearch
    volumes:
      - elasticsearch_volume:/opt/project
    env_file:
      - common.env
    expose:
     - "9200"
     - "9300"

  redis:
    labels:
        com.naxsoft.redis.description: "Data storage server"
    container_name: redis
    command: redis-server --appendonly yes
    build: redis
    volumes:
      - redis_volume:/opt/project
    expose:
      - "6379"
    env_file:
      - common.env
