version: '2'
volumes:
  elasticsearch_vol:
  redis_vol:
  logs_vol:

services:
  frontend:
    labels:
        com.naxsoft.frontend.description: "Web interface"
    container_name: frontend
    build: frontend
    ports:
      - "8080:8080"
      - "8000:8000"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    env_file:
      - common.env

  crawler:
    labels:
        com.naxsoft.crawler.description: "Web crawler and indexer"
    container_name: crawler
    build: crawler
    ports:
      - "8001:8000"
    links:
      - elasticsearch
      - redis:database
    depends_on:
      - elasticsearch
      - redis
      - tor-proxy
    env_file:
      - common.env

  elasticsearch:
    labels:
        com.naxsoft.elasticsearch.description: "Search engine"
    container_name: elasticsearch
    build: elasticsearch
    env_file:
      - common.env
    expose:
     - "9200"
     - "9300"

  redis:
    labels:
        com.naxsoft.redis.description: "Data storage server"
    container_name: redis
    command: redis-server --appendonly yes
    build: redis
    expose:
      - "6379"
    env_file:
      - common.env

  tor-proxy:
    image: arulrajnet/torprivoxy
    restart: always
    ports:
      - 8118:8118
      - 9050:9050
      - 9051:9051

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "Topic1:1:3,pages:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
