kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: aggress-dev
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # HTTP
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # HTTPS
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      # Frontend
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      # WebAdmin
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
      # Elasticsearch
      - containerPort: 30920
        hostPort: 9200
        protocol: TCP
      # Redis
      - containerPort: 30637
        hostPort: 6379
        protocol: TCP
  - role: worker
    labels:
      tier: worker
  - role: worker
    labels:
      tier: worker
networking:
  # Prevent conflicts with development services
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  # Use custom DNS to avoid conflicts
  dnsDomain: "aggress.local"
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://localhost:5000"]