#cloud-config
coreos:
  etcd2:
    discovery: "https://discovery.etcd.io/0a20472e461e2e17e20ed27f42d623da"
    listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
  fleet:
    public-ip: "$public_ipv4"
  flannel:
    etcd_prefix: "/naxsoft.com/cloud"
  update:
    reboot-strategy: "etcd-lock"
  units:
    - name: "docker-redis.service"
      command: "start"
      content: |
        [Unit]
        Description=Redis container
        Author=Me
        After=docker.service

        [Service]
        Restart=always
        ExecStart=/usr/bin/docker start -a redis_server
        ExecStop=/usr/bin/docker stop -t 2 redis_server
    - name: "etcd2.service"
      command: "start"
    - name: "fleet.service"
      command: "start"

ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeo2ZfnfXX+sD66eH5l4sO3DHdxgXqLQR764l298odyTkMQ7KrU9sgcjwKiYC5Te9z1ZNnj7z51R/ueeb6gYVRHHjxrpGPBzY7/d3vXXFKiwgqlm3tEdNu50ZmL2Qh6m9HYoRYcFfv7D3Pa5mL1cNi+mR5Cv6pajTHJNs8FQYvVc0VruKSJrVz2gVU0wcRDuNSrxCCn3SGA7sYk+LN05C8KLndQ+2S2Ifno9ZVvdh78xa9Uyc/n7ocF2lEH0J+LpMqFj9d3WXhkUiLs6bzNOrxh9YBasjBnrzweh/2nInTMDcDsqHGCydNYSKVO5bRai5YmyP7aogGL8iXZisNkL2p elendal@localhost.localdomain"

hostname: "coreos1"
users:
  - name: "elendal"
    groups:
      - "sudo"
      - "docker"
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeo2ZfnfXX+sD66eH5l4sO3DHdxgXqLQR764l298odyTkMQ7KrU9sgcjwKiYC5Te9z1ZNnj7z51R/ueeb6gYVRHHjxrpGPBzY7/d3vXXFKiwgqlm3tEdNu50ZmL2Qh6m9HYoRYcFfv7D3Pa5mL1cNi+mR5Cv6pajTHJNs8FQYvVc0VruKSJrVz2gVU0wcRDuNSrxCCn3SGA7sYk+LN05C8KLndQ+2S2Ifno9ZVvdh78xa9Uyc/n7ocF2lEH0J+LpMqFj9d3WXhkUiLs6bzNOrxh9YBasjBnrzweh/2nInTMDcDsqHGCydNYSKVO5bRai5YmyP7aogGL8iXZisNkL2p elendal@localhost.localdomain"

manage_etc_hosts: "localhost"
